### ISSUE TITLE
插件有些配置不当会，询问下什么样配置

### ISSUE THREAD

**Issue by konghao8013** [fanziwy/redmine_dingtalk#2]
1.企业Secret 是否为必填
2.回调url 填写什么，去哪儿获取
3.什么样验证是否配置成功
![image](https://github.com/user-attachments/assets/690606b8-2a36-4d53-9f3c-d23cf9b3013d)

**Comment by fanziwy** [comment]
1、企业Secret 是必填用于钉钉登陆
      相关钉钉文档：https://open.dingtalk.com/document/orgapp/obtain-identity-credentials
      企业Secret 在钉钉开放平台登陆后顶部 更多-》基本信息 -》开发信息（旧版）中还可以查到
2、回调url是redmine地址加/login,例  https://xxxx.com/login
3、能钉钉扫码登陆成功，同时发问题能收到钉钉的工作通知

**Comment by fanziwy** [comment]
插件中的应用ID，现在钉钉里面是 Client ID (原 AppKey 和 SuiteKey)了
应用Secret（appsecret）是 Client Secret (原 AppSecret 和 SuiteSecret)

**Comment by Teiya** [comment]
配置后提示无效的表单验证令牌，这个怎么解决

**Comment by fanziwy** [comment]
> 配置后提示无效的表单验证令牌，这个怎么解决

什么操作时出现这个提示？有没有相关截图

**Comment by Teiya** [comment]
> > 配置后提示无效的表单验证令牌，这个怎么解决
> 
> 什么操作时出现这个提示？有没有相关截图

钉钉好像有些api函数变了，修正上面的问题后还是无法在登录页面显示钉钉二维码登录。我自己用flask重写了插件

**Comment by fanziwy** [comment]
> > > 配置后提示无效的表单验证令牌，这个怎么解决
> > 
> > 
> > 什么操作时出现这个提示？有没有相关截图
> 
> 钉钉好像有些api函数变了，修正上面的问题后还是无法在登录页面显示钉钉二维码登录。我自己用flask重写了插件

好的，空了我再看看新接口，我公司之前开的钉钉应用，现在还是正常使用的，钉钉登陆、工作通知和钉钉代办都是正常的。

**Comment by fanziwy** [comment]
刚看了下钉钉文档，扫码登陆接口没有变化呢，估计是登陆回调地址不对。
回调url是redmine地址加/login,例 https://xxxx.com/login ，这个地址必须是跟访问地址同源

<img width="967" alt="image" src="https://github.com/user-attachments/assets/0b981d87-1438-4355-9340-eea3fde3c95f" />

相关文档地址：
https://open.dingtalk.com/document/orgapp/tutorial-obtaining-user-personal-information#title-90z-pr3-4gj
页面中的
内嵌二维码方式登录授权
